name: CMake

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S. -B_build -DCMAKE_INSTALL_PREFIX=_install

    - name: Build
      run: cmake --build _build

    - name: Install
      run: cmake --build _build --target install
